name: Deploy GitHub Pages (Dev stage)

on:
  push:
    branches:
      - dev

jobs:
  deploy-github-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: antongolub/action-setup-bun@v1
        with:
          bun-version: 0.2.2
          bun-config: '{"install": {"production": true}}'
          cache: true
          cache-bin: true
      - name: Install and Build
        run: |
          bun i
          sed -i 's/http:\/\/localhost:3001/https:\/\/docs.hubs-api.dev.xrcloud.belivvr.com/g' ./package.json
          bun run build
        env:
          CI: true
          DEPLOY_TARGET: gh-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
          clean: true
